# Generated by Django 3.2.5 on 2021-12-27 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='upvote',
        ),
        migrations.AddField(
            model_name='thread',
            name='catergories',
            field=models.CharField(choices=[('GAM', 'Games'), ('BUG', 'Bugs'), ('BAN', 'Banter'), ('GEN', 'General')], default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='thread',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('comment_content', models.TextField(max_length=255)),
                ('comment_atached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.thread')),
                ('comment_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
