# Generated by Django 3.2.5 on 2021-12-22 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='upvote',
            field=models.ManyToManyField(blank=True, default=False, related_name='thread_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
