# Generated by Django 3.2.5 on 2021-12-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_thread_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='catergories',
            field=models.CharField(choices=[('GAM', 'Games'), ('BUG', 'Bugs'), ('BAN', 'Banter'), ('GEN', 'General')], default='General', max_length=3),
        ),
    ]
