# Generated by Django 3.2.5 on 2021-12-23 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_alter_thread_catergories'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('comment_content', models.TextField(max_length=255)),
                ('comment_atached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.thread')),
                ('comment_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_upvote', models.ManyToManyField(blank=True, default=False, related_name='comment_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
