# Generated by Django 3.2.5 on 2021-12-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='excerpt',
        ),
    ]
