# Generated by Django 3.2.5 on 2021-12-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_comment_comment_atached_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-date_posted']},
        ),
    ]
